import enum

class DrawMode(enum.IntEnum):
    POINTS: int
    LINE_STRIP: int
    LINE_LOOP: int
    LINES: int
    LINE_STRIP_ADJACENCY: int
    LINES_ADJACENCY: int
    TRIANGLE_STRIP: int
    TRIANGLE_FAN: int
    TRIANGLES: int
    TRIANGLE_STRIP_ADJACENCY: int
    TRIANGLES_ADJACENCY: int
    PATCHES: int

class ElementsType(enum.IntEnum):
    UNSIGNED_BYTE: int
    UNSIGNED_SHORT: int
    UNSIGNED_INT: int

class ClearMask(enum.IntEnum):
    COLOR_BUFFER_BIT: int
    DEPTH_BUFFER_BIT: int
    STENCIL_BUFFER_BIT: int

def draw_arrays(mode: DrawMode, first: int, count: int) -> None: ...
def draw_arrays_instanced(mode: DrawMode, first: int, count: int, instance_count: int) -> None: ...
def draw_arrays_instanced_base_instance(mode: DrawMode, first: int, count: int, instance_count: int, base_count: int) -> None: ...

def draw_elements(mode: DrawMode, count: int, type: ElementsType) -> None: ...
def draw_elements_instanced(mode: DrawMode, count: int, type: ElementsType, prim_count: int) -> None: ...
def draw_elements_instanced_base_instance(mode: DrawMode, count: int, type: ElementsType, instance_count: int, base_instance: int) -> None: ...
def draw_elements_instanced_base_vertex(mode: DrawMode, count: int, type: ElementsType, instance_count: int, base_vertex: int) -> None: ...
def draw_elements_instanced_base_vertex_base_instance(mode: DrawMode, count: int, type: ElementsType, instance_count: int, base_vertex: int, base_instance: int) -> None: ...

def draw_arrays_indirect(mode: DrawMode) -> None: ...
def draw_elements_indirect(mode: DrawMode, type: ElementsType) -> None: ...

def multi_draw_arrays_indirect(mode: DrawMode, draw_count: int, stride: int) -> None: ...
def multi_draw_elements_indirect(mode: DrawMode, type: ElementsType, draw_count: int, stride: int) -> None: ...

def clear(mask: ClearMask) -> None: ...
