name: Push master
on:
  push

jobs:
  build-and-test:
    name: Build pygl and run all tests
    runs-on: windows-latest

    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v2.0.1
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          architecture: "x64"
          python-version: ${{matrix.python-version}}
          cache: "pip"
      - name: Build pygl
        run: |
        python -m pip install --upgrade pip
        pip install -v .[test]
      - name: Test pygl using pytest
        run: pytest tests
