name: Publish

on:
  release:
    types: [created]

  push:
    branches: ci-setup # TODO Change to `master` when branch completed
    paths-ignore:
      - 'tests/**'
      - '.gitignore'
      - '*.MD'

  pull_request:
    branches: ci-setup
    paths-ignore:
      - 'tests/**'
      - '.gitignore'
      - '*.MD'

jobs:
  publish:
    strategy:
      matrix:
        os: ['windows-latest', 'ubuntu-latest']
        python-version: ['3.13', '3.12']

    uses: ./.github/workflows/build.yml
    with:
      platform: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
