name: Publish

on:
  push:
    branches: ['ci-setup']

env:
  PYGL_BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, ubuntu-latest ]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyyaml packaging

      - name: Configure and build cmake (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        uses: threeal/cmake-action@v2.0.0
        with:
          build-dir: ./build/cmake/${{ env.PYGL_BUILD_TYPE }}
          options: |
            CMAKE_BUILD_TYPE=$PYGL_BUILD_TYPE
            CMAKE_VERBOSE_MAKEFILE=ON
          build-args: --config ${{ env.PYGL_BUILD_TYPE }}

      - name: Configure and build cmake (Windows)
        if: matrix.os == 'windows-latest'
        uses: threeal/cmake-action@v2.0.0
        with:
          build-dir: ./build/cmake
          options: |
            CMAKE_BUILD_TYPE=$PYGL_BUILD_TYPE
            CMAKE_VERBOSE_MAKEFILE=ON
          build-args: --config ${{ env.PYGL_BUILD_TYPE }}

      - name: Create wheel (Windows)
        if: matrix.os == 'windows-latest'
        id: wheel-windows
        run: |
          json = `python -m easywheel -B ./build/cmake`
          echo "WHL_FILEPATH=fromJson(json).whl_filepath" >> $env:GITHUB_OUTPUT
          echo "WHL_FILENAME=fromJson(json).whl_filename" >> $env:GITHUB_OUTPUT

      - name: Create wheel (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        id: wheel-ubuntu
        run: |
          json = `python -m easywheel -B ./build/cmake`
          echo "WHL_FILEPATH=fromJson(json).whl_filepath" >> $GITHUB_OUTPUT
          echo "WHL_FILENAME=fromJson(json).whl_filename" >> $GITHUB_OUTPUT

      - name: Upload artifacts (Windows)
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.wheel-windows.outputs.WHL_FILENAME }}
          path: ${{ steps.wheel-windows.outputs.WHL_FILEPATH }}

      - name: Upload artifacts (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.wheel-ubuntu.outputs.WHL_FILENAME }}
          path: ${{ steps.wheel-ubuntu.outputs.WHL_FILEPATH }}

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts


