name: Publish

on:
  push:
    branches: ['ci-setup']

env:
  PYGL_BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyyaml packaging

      - name: Configure and build cmake
        uses: threeal/cmake-action@v2.0.0
        with:
          build-dir: build/cmake
          options: |
            CMAKE_BUILD_TYPE=$PYGL_BUILD_TYPE

      - name: Create wheel
        id: wheel
        run: |
          whl_filepath="python -m easywheel -B build/cmake"
          echo WHL_FILEPATH=$whl_filepath >> $GITHUB_OUTPUT

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheel-${{ matrix.os }}-${{ github.sha }}
          path: ${{ steps.wheel.outputs.WHL_FILEPATH }}

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts


